version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=pass
      - DB_URI=postgres://postgres:postgres@database:5432/cognilytics_mis
      - USE_MOCK_DATA=false
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=cognilytics_mis
      - DB_PORT=5432
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules

  database:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cognilytics_mis
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

volumes:
  pgdata:
